### ISSUE TITLE
Synchrotron: Add linking device logic

### ISSUE THREAD

**Issue by abbiemery** [dls-controls/tickit-devices#22]
As stated in the README, the Synchrotron device is just a collection of unconnected simualted iocs. The topup, currrent, countdowns etc all have behavior that can be simulated and linked with the inputs & output busses.

**Comment by abbiemery** [comment]
As stated in issue #3 , the goal was a minimum working device. It would be ideal to now have the device behave slighlty more naturally and implement the topup gating behaviour of the records

Required:

    Include internal logic to link the top-up timers and the current (See high level apps confluence for Top UP gating).

**Comment by DominicOram** [comment]
For testing Artemis it would be useful to have a backdoor for this (https://github.com/dls-controls/tickit/issues/83 is the best way to do this but in the meantime we can just have a PV that we can write to from ophyd)

**Comment by abbiemery** [comment]
Something else that would be nice for this ticket : Changing the PV names to all be prefixed with `S03-SIM` (or something similar)  instead of `BL03S`, since `BL03S`  is a beamline prefix and the synchrotron is beamline agnostic.

**Comment by JimboMonkey** [comment]
I think the machine PVs within 'synchrotron' should stay as close to the 'real' PVs as possible, but with some kind of designation of simulation in there.  eg SR-CS-FILL-01:ENDCOUNTDN could become SR-SIM-FILL-01:ENDCOUNTDN, and CS-CS-MSTAT-01:MODE could become CS-SIM-MSTAT-01:MODE

**Comment by abbiemery** [comment]
@evalott100 is this finished? Please may you check over it and close it if so.
