### ISSUE TITLE
Eiger ZMQ broken against tickit master

### ISSUE THREAD

**Issue by callumforrester** [dls-controls/tickit-devices#91]
The detector does not seem to send any signals via ZeroMQ when running against tickit master, to be investigated.

**Comment by GDYendell** [comment]
I think I know why this is. I had the same issue when adding support for stream2. I didn't quite finish it, but I could make a PR with just the fix if that is useful?

**Comment by callumforrester** [comment]
Yes please!

**Comment by GDYendell** [comment]
Added #92 because tickit-devices doesn't currently work against the latest tickit. Added #93 to fix this issue.
